name: pomodoro_mobile
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  retrofit: '>=3.0.0 <4.0.0'

  flutter_bloc: ^8.0.1

  provider: ^6.0.3

  equatable: ^2.0.3

  url_launcher: ^6.1.2

  fluttertoast: ^8.0.9

  cupertino_icons: ^1.0.2

  json_serializable: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '^4.0.1'
  build_runner: '^2.1.7'
  flutter_lints: ^2.0.0
  intl: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
